default:
  @just --list

apps:
  flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  flatpak install -uy com.usebottles.bottles
  flatpak install -uy com.github.tchx84.Flatseal
  flatpak install -uy org.gnome.gitlab.YaLTeR.VideoTrimmer

bios:
  systemctl reboot --firmware-setup

switch:
  flake switch ~/.config/flake#

home-switch:
  home-manager switch

update:
  #!/usr/bin/env bash
  cd ~/.config/flake
  flake update
  flake switch
  cd ~/.config/home-manager
  flake update
  home-manager switch
  flatpak update -y

